const { admin } = require("../config/supabase"); const { ok, fail } = require("../utils/response"); const cache=require("../utils/memoryCache");
const CATEGORY_CACHE="categories:all",clearCategories=()=>cache.remove(CATEGORY_CACHE);
exports.list=async(req,res,next)=>{try{let data=cache.get(CATEGORY_CACHE);if(!data){const result=await admin.from("categories").select("*,subcategories(*)").order("name");if(result.error)throw result.error;data=cache.set(CATEGORY_CACHE,result.data,30000)}ok(res,"Categories fetched successfully",data)}catch(e){next(e)}};
exports.get=async(req,res,next)=>{try{const {data,error}=await admin.from("categories").select("*,subcategories(*)").eq("id",req.params.id).single();if(error)return fail(res,"Category not found",[],404);ok(res,"Category fetched successfully",data)}catch(e){next(e)}};
exports.create=async(req,res,next)=>{try{const {data,error}=await admin.from("categories").insert({name:req.body.name,description:req.body.description||null}).select().single();if(error)throw error;clearCategories();ok(res,"Category created successfully",data,201)}catch(e){next(e)}};
exports.update=async(req,res,next)=>{try{const {data,error}=await admin.from("categories").update({name:req.body.name,description:req.body.description||null}).eq("id",req.params.id).select().single();if(error)return fail(res,"Category not found",[],404);clearCategories();ok(res,"Category updated successfully",data)}catch(e){next(e)}};
exports.remove=async(req,res,next)=>{try{const {count,error}=await admin.from("products").select("id",{count:"exact",head:true}).eq("category_id",req.params.id).neq("status","inactive");if(error)throw error;if(count)return fail(res,"Category is in use by active products",[],409);const {error:del}=await admin.from("categories").delete().eq("id",req.params.id);if(del)throw del;clearCategories();ok(res,"Category deleted successfully",{})}catch(e){next(e)}};
exports.addSubcategory=async(req,res,next)=>{try{const {data,error}=await admin.from("subcategories").insert({category_id:req.params.id,name:req.body.name}).select().single();if(error)throw error;clearCategories();ok(res,"Subcategory created successfully",data,201)}catch(e){next(e)}};
exports.removeSubcategory=async(req,res,next)=>{try{const {error}=await admin.from("subcategories").delete().eq("id",req.params.subcategoryId);if(error)throw error;clearCategories();ok(res,"Subcategory deleted successfully",{})}catch(e){next(e)}};
