const { admin }=require("../config/supabase"),{ok,fail}=require("../utils/response"),{uploadImage}=require("../services/storageService");const select="*,category:categories(id,name),subcategory:subcategories(id,name)";
const normalizePartCode=value=>{const normalized=String(value||"").trim().toUpperCase();return normalized||null};
const searchTerm=value=>String(value||"").trim().replace(/[%,()]/g," ");
exports.list=async(req,res,next)=>{try{const page=Math.max(1,+req.query.page||1),limit=Math.min(100,Math.max(1,+req.query.limit||20)),search=searchTerm(req.query.search);let q=admin.from("products").select(select,{count:"exact"});if(search)q=q.or(`name.ilike.%${search}%,sku.ilike.%${search}%,part_code.ilike.%${search}%`);if(req.query.category)q=q.eq("category_id",req.query.category);if(req.query.subcategory)q=q.eq("subcategory_id",req.query.subcategory);if(req.query.status)q=q.eq("status",req.query.status);if(req.query.stockStatus==="out_of_stock")q=q.eq("quantity",0);const {data,count,error}=await q.order(["name","quantity","price","created_at"].includes(req.query.sortBy)?req.query.sortBy:"created_at",{ascending:req.query.sortOrder==="asc"}).range((page-1)*limit,page*limit-1);if(error)throw error;const products=(data||[]).filter(p=>req.query.stockStatus!=="low_stock"|| (p.quantity>0&&p.quantity<=p.low_stock_threshold));ok(res,"Products fetched successfully",{products,pagination:{page,limit,total:req.query.stockStatus==="low_stock"?products.length:count,totalPages:req.query.stockStatus==="low_stock"?1:Math.ceil(count/limit)}})}catch(e){next(e)}};
exports.get=async(req,res,next)=>{try{const {data,error}=await admin.from("products").select(select).eq("id",req.params.id).single();if(error)return fail(res,"Product not found",[],404);ok(res,"Product fetched successfully",data)}catch(e){next(e)}};
exports.create=async(req,res,next)=>{try{const b=req.body,image=await uploadImage("product-images",req.file,"products"),{data:id,error}=await admin.rpc("create_product_with_opening",{p_name:b.name,p_part_code:normalizePartCode(b.partCode),p_price:b.price,p_description:b.description||null,p_image_url:image,p_category_id:b.categoryId||null,p_subcategory_id:b.subcategoryId||null,p_low_stock_threshold:+b.lowStockThreshold||0,p_status:b.status||"active",p_opening_quantity:+b.openingQuantity||0,p_created_by:req.user.id});if(error)throw error;const {data, error:fetchError}=await admin.from("products").select(select).eq("id",id).single();if(fetchError)throw fetchError;ok(res,"Product created successfully",data,201)}catch(e){next(e)}};
exports.update=async(req,res,next)=>{try{const b=req.body,image=await uploadImage("product-images",req.file,"products"),payload={name:b.name,part_code:normalizePartCode(b.partCode),price:b.price,description:b.description||null,category_id:b.categoryId||null,subcategory_id:b.subcategoryId||null,low_stock_threshold:+b.lowStockThreshold||0,status:b.status||"active"};if(image)payload.image_url=image;const {data,error}=await admin.from("products").update(payload).eq("id",req.params.id).select(select).single();if(error)throw error;ok(res,"Product updated successfully",data)}catch(e){next(e)}};
exports.remove=async(req,res,next)=>{try{const {count,error:historyError}=await admin.from("transaction_items").select("id",{count:"exact",head:true}).eq("product_id",req.params.id);if(historyError)throw historyError;if(count)return fail(res,"This product has stock movement history and cannot be permanently deleted. Its transaction record is preserved for audit accuracy.",[],409);const {data,error}=await admin.from("products").delete().eq("id",req.params.id).select("id").maybeSingle();if(error)throw error;if(!data)return fail(res,"Product not found",[],404);ok(res,"Product permanently deleted",{},200)}catch(e){next(e)}};
exports.transactions=async(req,res,next)=>{try{const {data,error}=await admin.from("transaction_items").select("*,transaction:transactions(*)").eq("product_id",req.params.id).order("created_at",{ascending:false});if(error)throw error;ok(res,"Product transactions fetched successfully",data)}catch(e){next(e)}};
